version: '3.9'
services:
  postgres:
    container_name: postgres-momentum
    image: postgres:16.5
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin-momentum
    image: dpage/pgadmin4:8.6
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
networks:
  postgres:
    driver: bridge